spring:
  r2dbc:
    driver: "postgresql"
    username: "postgres"
    password: "Shoxruh0912"
    url: r2dbc:postgresql://localhost:5432/affiliation
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
      enabled: true
      file-size-threshold: 2KB

springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api/doc

justice:
  api:
    base-url: "/nimadr3"
    apis:
      check-api: "/nimadr"