spring:
  application:
    name: ${APP_NAME:affiliation-application}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  r2dbc:
    driver: "postgresql"
    username: "postgres"
    password: "Shoxruh0912"
    url: r2dbc:postgresql://localhost:5432/affiliation
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB
      enabled: true
      file-size-threshold: 2KB
springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /api/doc

justice:
  request:
    json-rpc: 2.0
    method: 12341234
  api:
    key: 12341234
    base-url: 12342134

etp:
  rabbit:
    consumer-queue-name: 123
    publisher-exchange-name: 123
    publisher-routing-key: 123

server:
  port: ${APP_PORT:7000}